# Generated by Django 4.2 on 2026-02-14 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_cartitem_size_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
