# Generated by Django 4.2 on 2026-02-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='delivered_at',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='status',
        ),
    ]
