# Generated by Django 4.2 on 2026-01-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_brand_slug_category_slug_product_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(default='men', max_length=20),
            preserve_default=False,
        ),
    ]
