# Generated by Django 4.2 on 2026-02-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_color_productvariant_variantimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
