# Generated by Django 4.2 on 2026-02-03 03:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_serviceablepincode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceablepincode',
            name='cod_available',
        ),
        migrations.RemoveField(
            model_name='serviceablepincode',
            name='eta_days',
        ),
        migrations.CreateModel(
            name='ProductPincodeAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_available', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('cod_available', models.BooleanField(default=True)),
                ('eta_days', models.PositiveIntegerField(default=3)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_availability', to='products.serviceablepincode')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pincode_availability', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'pincode')},
            },
        ),
    ]
