# Generated by Django 4.2 on 2026-02-07 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_remove_serviceablepincode_cod_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_products', to='products.color'),
        ),
    ]
